trigger:
  batch: true

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

jobs:
  - job: container_job
    displayName: Container Job
    pool:
      name: Azure Pipelines
      vmImage: ubuntu-18.04
    container:
      image: terragrunt-azure-live-example:latest
      endpoint: linuxcave_acr
    steps:
      - bash: terragrunt plan
        workingDirectory: src/prd/kubernetes/upstream
        displayName: Terragrunt Plan
      - bash: terragrunt apply
        workingDirectory: src/prd/kubernetes/upstream
        displayName: Terragrunt Apply
        condition: eq(variables.isMain, true)
