trigger:
  batch: true

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  - group: azurerm
    # ARM_STORAGE_ACCOUNT_NAME
    # ARM_ACCESS_KEY
    # ARM_STORAGE_ACCOUNT_CONTAINER
  - group: linuxcave-prd
    # ARM_CLIENT_ID
    # ARM_CLIENT_SECRET
    # ARM_SUBSCRIPTION_ID
    # ARM_TENANT_ID

jobs:
  - job: container_job
    displayName: Container Job
    pool:
      name: Azure Pipelines
      vmImage: ubuntu-18.04
    container:
      image: terragrunt-azure-live-example:latest
      endpoint: linuxcave_acr
    steps:
      - bash: terragrunt plan
        workingDirectory: src/prd/kubernetes/upstream
        displayName: Terragrunt Plan
        env:
          ARM_STORAGE_ACCOUNT_NAME: $(ARM_STORAGE_ACCOUNT_NAME)
          ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)
          ARM_STORAGE_ACCOUNT_CONTAINER: $(ARM_STORAGE_ACCOUNT_CONTAINER)
          ARM_CLIENT_ID: $(ARM_CLIENT_ID)
          ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
          ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
          ARM_TENANT_ID: $(ARM_TENANT_ID)
