version: '3.8'
services:
  terragrunt-azure-live-example:
    environment:
      # ------------------------------
      # Required environment variables
      # ------------------------------
      # Terraform remote state
      ARM_STORAGE_ACCOUNT_NAME: ${ARM_STORAGE_ACCOUNT_NAME}
      ARM_ACCESS_KEY: ${ARM_ACCESS_KEY}
      ARM_STORAGE_ACCOUNT_CONTAINER: ${ARM_STORAGE_ACCOUNT_CONTAINER}
      # k8s
      DATADOG_API_KEY: ${DATADOG_API_KEY}
      GIT_AUTHUSER: ${GIT_AUTHUSER}
      GIT_AUTHKEY: ${GIT_AUTHKEY}
      GHCR_USER: ${GHCR_USER}
      GHCR_PASSWORD: ${GHCR_PASSWORD}
