apiVersion: apps/v1
kind: Deployment
metadata:
  name: apollo-server
  namespace: linuxcaveprd-scratch
spec:
  replicas: 2
  selector:
    matchLabels:
      service: apollo-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        service: apollo-server
    spec:
      restartPolicy: Always
      containers:
        - name: apollo-server
          image: ghcr.io/linuxcave/apollo-server:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          livenessProbe:
            httpGet:
              path: /liveness
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /readiness
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 1
          env:
            # Node
            - name: NODE_ENV
              value: production
            # Service
            - name: SERVICE
              value: apollo-server
            - name: PORT
              value: "4000"
            - name: ENDPOINT
              value: https://apollo-server.linuxcave.io
            # Datadog
            - name: DD_ENV
              value: "production"
            - name: DD_TRACE_ENABLED
              value: "true"
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_RUNTIME_METRICS_ENABLED
              value: "true"
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
      imagePullSecrets:
        - name: regcred
