trigger:
  batch: true

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

jobs:
  - job: container_job
    displayName: Container Job
    pool:
      name: Azure Pipelines
      vmImage: ubuntu-18.04
    container:
      image: terragrunt-azure-live-example:azure-pipelines
      endpoint: linuxcave_acr
    steps:
      - bash: echo hello
      - bash: echo world
        condition: eq(variables.isMain, true)

